init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
    - servicing/1.0.x
build_script:
  - build.cmd /p:Configuration=Release
clone_depth: 1
test: off
deploy: off
os: Visual Studio 2017
